<!DOCTYPE html>
<html>

<head>
    % include('./static/base/header.tpl', title = 'Attendance Management')
</head>

<body id="page-top">
    <div id="wrapper">
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <div class="container-fluid">
                    <div class="row text-center">
                        <div class="col"><img src="/logo/Masatrek.png" style="max-width: 500px;margin: 50px;" /></div>
                    </div>
                    <h3 class="text-center text-dark mb-4">ATTENDANCE REPORT</h3>
                    <h3 class="text-center text-dark mb-4">2021-10-20 <strong>TO</strong> 2021-10-30</h3>
                    <h6 class="text-center text-dark mb-4">Generated By : Haziq Norisham</h6>
                    <div class="card shadow-none">
                        <div class="card-header py-3">
                            <p class="text-primary d-xxl-flex justify-content-xxl-center m-0 fw-bold">EmployeeAttendance</p>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive table mt-2" id="dataTable" role="grid" aria-describedby="dataTable_info">
                                <table class="table my-0" id="dataTable">
                                    <thead>
                                        <tr>
                                            <th>Date</th>
                                            <th>Name</th>
                                            <th>Employee ID</th>
                                            <th>Entry Time</th>
                                            <th>Terminal</th>
                                            <th>Leave Time</th>
                                            <th>Terminal</th>
                                            <th>Location</th>
                                            <th>Notes</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>2021-10-22</td>
                                            <td><img class="rounded-circle me-2" width="30" height="30" src="snapshot/2021-10-18T12_35_07.jpg" data-user_id="100" data-date="2021-10-22" data-bs-toggle="modal" data-bs-target="#modal-1" onclick="detailed_view(this)">Haziq Norisham</td>
                                            <td>emp-001</td>
                                            <td><p class="text-danger">2021-10-22 10:00:18</p></td>
                                            <td>Demo Terminal(0)</td>
                                            
                                            <td><p class="text-danger">2021-10-22 11:12:02</p></td>
                                            <td>Demo Terminal(0)</td>
                                            <td>None</td>
                                            <td>
                                                No File uploaded
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>2021-10-21</td>
                                            <td><img class="rounded-circle me-2" width="30" height="30" src="snapshot/2021-10-18T12_35_07.jpg" data-user_id="100" data-date="2021-10-21" data-bs-toggle="modal" data-bs-target="#modal-1" onclick="detailed_view(this)">Haziq Norisham</td>
                                            <td>emp-001</td>
                                            <td><p class="text-danger">2021-10-21 09:26:25</p></td>
                                            <td>Demo Terminal(0)</td>
                                            
                                            <td><p class="text-danger">2021-10-21 09:26:25</p></td>
                                            <td>Demo Terminal(0)</td>
                                            <td>None</td>
                                            <td>
                                                No File uploaded
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>2021-10-20</td>
                                            <td><img class="rounded-circle me-2" width="30" height="30" src="snapshot/2021-10-18T12_35_07.jpg" data-user_id="100" data-date="2021-10-20" data-bs-toggle="modal" data-bs-target="#modal-1" onclick="detailed_view(this)">Haziq Norisham</td>
                                            <td>emp-001</td>
                                            <td><p class="text-danger">2021-10-20 11:48:55</p></td>
                                            <td>Demo Terminal(0)</td>
                                            
                                            <td><p class="text-danger">2021-10-20 16:59:29</p></td>
                                            <td>Demo Terminal(0)</td>
                                            <td>asdfsdaf</td>
                                            <td>
                                                <a href="/uploads/1052804fce3b4d76b9f2eb0aef0853dd/image.jpg" target="_blank">uploaded file</a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>2021-10-20</td>
                                            <td><img class="rounded-circle me-2" width="30" height="30" src="snapshot/2021-10-18T09_42_36.jpg" data-user_id="102" data-date="2021-10-20" data-bs-toggle="modal" data-bs-target="#modal-1" onclick="detailed_view(this)">Ahmad</td>
                                            <td>emp-002</td>
                                            <td><p class="text-danger">2021-10-20 11:48:55</p></td>
                                            <td>Demo Terminal(0)</td>
                                            
                                            <td><p class="text-danger">2021-10-20 16:59:29</p></td>
                                            <td>Demo Terminal(0)</td>
                                            <td>None</td>
                                            <td>
                                                No File uploaded
                                            </td>
                                        </tr>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>Date</th>
                                            <th>Name</th>
                                            <th>Employee ID</th>
                                            <th>Entry Time</th>
                                            <th>Terminal</th>
                                            <th>Leave Time</th>
                                            <th>Terminal</th>
                                            <th>Location</th>
                                            <th>Notes</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <footer class="bg-white sticky-footer">
                <div class="container my-auto">
                    <div class="text-center my-auto copyright"><span>Copyright © Masatrek 2021</span></div>
                </div>
            </footer>
        </div>
    </div>
    <div role="dialog" tabindex="-1" class="modal fade" id="modal-1">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Detailed View - MUHAMMAD HAZIQ BIN NORISHAM</h4><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Timestamp</th>
                                    <th>Location</th>
                                    <th>Temperature</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>2021-10-11 11:27:22</td>
                                    <td>Main Entrance</td>
                                    <td>36.6 °C<br /></td>
                                </tr>
                                <tr>
                                    <td>2021-10-11 12:14:00<br /></td>
                                    <td>Side Entrance</td>
                                    <td>35.2</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Close</button></div>
            </div>
        </div>
    </div>
</body>
<script>
    window.onload = function() {
        window.print();
    };
</script>
</html>